export const APPLICATION_CREATE_REQUEST = 'APPLICATION_CREATE_REQUEST';
export const APPLICATION_CREATE_SUCCESS = 'APPLICATION_CREATE_SUCCESS';
export const APPLICATION_CREATE_FAIL = 'APPLICATION_CREATE_FAIL';